apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest10
  labels:
    app: rest10
spec:
  #replicas: 2
  
  selector:
    matchLabels:
      app: rest10
  template:
    metadata:
      labels:
        app: rest10
    spec:
      containers:
      - name: myapp
        image: dhruvpjoshi1999/db:dhruv
        ports:
        - containerPort: 8000
     # nodeSelector:
      #  name: dhruv
   
---
# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
   #type: LoadBalancer
  selector:
    app: rest10
  ports:
  - port: 8000
    targetPort: 8000
      # nodePort: 30090
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
#  metadata:
#    name: rest
# spec:
#    ingressClassName: traefik
#    rules:
#    - http:
#        paths:
#        - pathType: Prefix
#          path: 
#          backend:
#           service:
#              name: dhruv4-service
#              port:
#               number: 8000
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: rest
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: traefik
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: dhruv4-service
#             port:
#               number: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  selector:
    matchLabels:
      app: postgres-statefulset
  serviceName: postgres-service
  template:
    metadata: 
      labels:
        app: postgres-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB 
            value: mydatabase
          - name: POSTGRES_USER
            value: dhruv
          - name : POSTGRES_PASSWORD
            value: mypassword
       
        volumeMounts:
            - name: postgre-pvctemplates
              mountPath: /var/lib/pgsql/data 
#      nodeSelector:
 #       name: dhruv        
  volumeClaimTemplates:
  - metadata: 
      name: postgre-pvctemplates
    spec:
      storageClassName: "local-path"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion : v1
kind : ConfigMap
metadata:
  name : postgres
data:
   DB_HOST: dhruv
   DB_NAME: mydatabase
   DB_PORT: '3306'
   PORT: '8000'
   MARIADB_DATABASE: mydp
   MARIADB_USER: dhruv


